services:
  coredns:
    # 
    # git clone https://github.com/coredns/coredns.git
    # cd coredns
    # setenv CFLAGS "-O3 -pipe -march=native -mtune=native" ... 多分効いてない...orz
    # make
    # echo 'VOLUME ["/etc/coredns"]'                >> Dockerfile
    # echo 'CMD ["-conf", "/etc/coredns/Corefile"]' >> Dockerfile
    #
    # setenv HASH `git log | awk 'NR==1{print $2}'`
    # docker buildx build . -t 1yen00docker/coredns:$HASH
    #
    # docker push 1yen00docker/coredns:$HASH
    #
    image: 1yen00docker/coredns:0ed689e2d0401bc91b0876f3c0f41c89bbf83b34
    container_name: dns
    logging:
      driver: "local"
    restart: on-failure
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './config:/etc/coredns'

