services:
  coredns:
    #
    # config/Corefile : 設定ファイル
    # config/hosts : 読み込んで DNS で応答 (/etc/hosts とハードリンクしておくと便利)
    # 
    # need go-lang https://go.dev/doc/install
    #
    # git clone https://github.com/coredns/coredns.git
    #
    # ブランチを指定して clone する場合
    # git clone https://github.com/coredns/coredns.git -b master v1.12.0
    #
    # cd coredns
    # setenv CFLAGS "-O3 -pipe -march=native -mtune=native" ... 多分効いてない...orz
    # make
    # echo 'VOLUME ["/etc/coredns"]'                >> Dockerfile
    # echo 'CMD ["-conf", "/etc/coredns/Corefile"]' >> Dockerfile
    #
    # setenv HASH `git log | awk 'NR==1{print $2}'`
    # docker buildx build . -t 1yen00docker/coredns:$HASH
    #
    # docker push 1yen00docker/coredns:$HASH
    #
    image: 1yen00docker/coredns:v1.12.0
    container_name: dns
    logging:
      driver: "local"
    restart: always
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './config:/etc/coredns'
