services:
  coredns:
    #
    # config/Corefile : 設定ファイル
    # config/hosts : 読み込んで DNS で応答 (/etc/hosts とハードリンクしておくと便利)
    # 
    # need go-lang https://go.dev/doc/install
    #
    # git clone https://github.com/coredns/coredns.git
    #
    # ブランチを指定して clone する場合
    # git clone https://github.com/coredns/coredns.git -b master v1.12.2
    #
    # cd coredns

    ## GHSA-2464-8j7c-4cjm 対応 (go-viper/mapstructure/v2@v2.3.0 以前)
    ## アップデート
    ## go get github.com/go-viper/mapstructure/v2@v2.4.0
    ##
    ## 依存関係を最適化
    ## go mod tidy
    ##
    ## バージョンの確認
    ## go list -m all | grep mapstructure

    # setenv CFLAGS "-O3 -pipe -march=native -mtune=native" ... 多分効いてない...orz
    # make
    # echo 'VOLUME ["/etc/coredns"]'                >> Dockerfile
    # echo 'CMD ["-conf", "/etc/coredns/Corefile"]' >> Dockerfile
    #
    # setenv HASH `git rev-parse HEAD`
    # docker buildx build . -t 1yen00docker/coredns:$HASH -t 1yen00docker/coredns:1yen00_v1.12.3
    #
    # // docker push 1yen00docker/coredns:$HASH
    # docker push 1yen00docker/coredns:1yen00_v1.12.3
    #
    

    image: 1yen00docker/coredns:1yen00_v1.12.3
    container_name: dns
    restart: always
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './config:/etc/coredns'
    logging:  
      # driver: "local"   # ローカルドライバを使用するなら以下を削除
      driver: "syslog"  # syslog でログを送信する
      options:
        syslog-address: "tcp://192.168.0.252:514"
        syslog-facility: "daemon"
        syslog-format: "rfc5424"
        tag: "CoreDNS"
